//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickLaunchOnTray.Resources {
    using System;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickLaunchOnTray.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find &apos;config.ini&apos; file:\n{0}.
        /// </summary>
        internal static string ConfigFileNotFound {
            get {
                return ResourceManager.GetString("ConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;config.ini&apos; 파일을 찾을 수 없습니다:\n{0}.
        /// </summary>
        internal static string ConfigFileNotFound_ko {
            get {
                return ResourceManager.GetString("ConfigFileNotFound_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while reading configuration file..
        /// </summary>
        internal static string ConfigReadError {
            get {
                return ResourceManager.GetString("ConfigReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 설정 파일을 읽는 중 오류가 발생했습니다..
        /// </summary>
        internal static string ConfigReadError_ko {
            get {
                return ResourceManager.GetString("ConfigReadError_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 확인.
        /// </summary>
        internal static string Confirm_ko {
            get {
                return ResourceManager.GetString("Confirm_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to terminate &apos;QuickLaunchOnTray&apos;? All quick launch icons will disappear..
        /// </summary>
        internal static string ConfirmTermination {
            get {
                return ResourceManager.GetString("ConfirmTermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;QuickLaunchOnTray&apos;를 종료하시겠습니까? 모든 빠른 실행 아이콘이 사라집니다..
        /// </summary>
        internal static string ConfirmTermination_ko {
            get {
                return ResourceManager.GetString("ConfirmTermination_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run program: {0}.
        /// </summary>
        internal static string CannotRunProgram {
            get {
                return ResourceManager.GetString("CannotRunProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프로그램을 실행할 수 없습니다: {0}.
        /// </summary>
        internal static string CannotRunProgram_ko {
            get {
                return ResourceManager.GetString("CannotRunProgram_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path is empty..
        /// </summary>
        internal static string EmptyPath {
            get {
                return ResourceManager.GetString("EmptyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 경로가 비어있습니다..
        /// </summary>
        internal static string EmptyPath_ko {
            get {
                return ResourceManager.GetString("EmptyPath_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 오류.
        /// </summary>
        internal static string Error_ko {
            get {
                return ResourceManager.GetString("Error_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no information about the program to run in the &apos;config.ini&apos; file..
        /// </summary>
        internal static string NoProgramInfo {
            get {
                return ResourceManager.GetString("NoProgramInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;config.ini&apos; 파일에 실행할 프로그램 정보가 없습니다..
        /// </summary>
        internal static string NoProgramInfo_ko {
            get {
                return ResourceManager.GetString("NoProgramInfo_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 폴더 열기.
        /// </summary>
        internal static string OpenFolder_ko {
            get {
                return ResourceManager.GetString("OpenFolder_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path does not exist: {0}.
        /// </summary>
        internal static string PathNotExist {
            get {
                return ResourceManager.GetString("PathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 경로가 존재하지 않습니다: {0}.
        /// </summary>
        internal static string PathNotExist_ko {
            get {
                return ResourceManager.GetString("PathNotExist_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while running program: {0}.
        /// </summary>
        internal static string ProgramRunError {
            get {
                return ResourceManager.GetString("ProgramRunError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프로그램 실행 중 오류가 발생했습니다: {0}.
        /// </summary>
        internal static string ProgramRunError_ko {
            get {
                return ResourceManager.GetString("ProgramRunError_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run this program.
        /// </summary>
        internal static string RunProgram {
            get {
                return ResourceManager.GetString("RunProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 프로그램 실행.
        /// </summary>
        internal static string RunProgram_ko {
            get {
                return ResourceManager.GetString("RunProgram_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate &apos;QuickLaunchOnTray&apos;.
        /// </summary>
        internal static string TerminateApp {
            get {
                return ResourceManager.GetString("TerminateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;QuickLaunchOnTray&apos; 종료.
        /// </summary>
        internal static string TerminateApp_ko {
            get {
                return ResourceManager.GetString("TerminateApp_ko", resourceCulture);
            }
        }
    }
} 