//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickLaunchOnTray.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickLaunchOnTray.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cannot run program: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CannotRunProgram {
            get {
                return ResourceManager.GetString("CannotRunProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로그램을 실행할 수 없습니다: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CannotRunProgram_ko {
            get {
                return ResourceManager.GetString("CannotRunProgram_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   닫기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Close_ko {
            get {
                return ResourceManager.GetString("Close_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find &apos;config.ini&apos; file: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigFileNotFound {
            get {
                return ResourceManager.GetString("ConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;config.ini&apos; 파일을 찾을 수 없습니다: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigFileNotFound_ko {
            get {
                return ResourceManager.GetString("ConfigFileNotFound_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occurred while reading configuration file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigReadError {
            get {
                return ResourceManager.GetString("ConfigReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정 파일을 읽는 중 오류가 발생했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfigReadError_ko {
            get {
                return ResourceManager.GetString("ConfigReadError_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Confirm_ko {
            get {
                return ResourceManager.GetString("Confirm_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to terminate &apos;QuickLaunchOnTray&apos;? All quick launch icons will disappear.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfirmTermination {
            get {
                return ResourceManager.GetString("ConfirmTermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;QuickLaunchOnTray&apos;를 종료하시겠습니까? 모든 빠른 실행 아이콘이 사라집니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ConfirmTermination_ko {
            get {
                return ResourceManager.GetString("ConfirmTermination_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path is empty.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EmptyPath {
            get {
                return ResourceManager.GetString("EmptyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경로가 비어있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EmptyPath_ko {
            get {
                return ResourceManager.GetString("EmptyPath_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_ko {
            get {
                return ResourceManager.GetString("Error_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error building folder menu: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorBuildingFolderMenu {
            get {
                return ResourceManager.GetString("ErrorBuildingFolderMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   폴더 메뉴 구성 중 오류 발생: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorBuildingFolderMenu_ko {
            get {
                return ResourceManager.GetString("ErrorBuildingFolderMenu_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error showing folder menu: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorShowingFolderMenu {
            get {
                return ResourceManager.GetString("ErrorShowingFolderMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   폴더 메뉴 표시 중 오류 발생: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ErrorShowingFolderMenu_ko {
            get {
                return ResourceManager.GetString("ErrorShowingFolderMenu_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   불러오는 중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Loading_ko {
            get {
                return ResourceManager.GetString("Loading_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No items available과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoItemsAvailable {
            get {
                return ResourceManager.GetString("NoItemsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   표시할 항목이 없습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoItemsAvailable_ko {
            get {
                return ResourceManager.GetString("NoItemsAvailable_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no information about the program to run in the &apos;config.ini&apos; file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoProgramInfo {
            get {
                return ResourceManager.GetString("NoProgramInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;config.ini&apos; 파일에 실행할 프로그램 정보가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoProgramInfo_ko {
            get {
                return ResourceManager.GetString("NoProgramInfo_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   폴더 열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenFolder_ko {
            get {
                return ResourceManager.GetString("OpenFolder_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open in Explorer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenInExplorer {
            get {
                return ResourceManager.GetString("OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   탐색기에서 열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpenInExplorer_ko {
            get {
                return ResourceManager.GetString("OpenInExplorer_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path does not exist: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PathNotExist {
            get {
                return ResourceManager.GetString("PathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경로가 존재하지 않습니다: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PathNotExist_ko {
            get {
                return ResourceManager.GetString("PathNotExist_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occurred while running program: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProgramRunError {
            get {
                return ResourceManager.GetString("ProgramRunError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로그램 실행 중 오류가 발생했습니다: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProgramRunError_ko {
            get {
                return ResourceManager.GetString("ProgramRunError_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run this program과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RunProgram {
            get {
                return ResourceManager.GetString("RunProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로그램 실행과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RunProgram_ko {
            get {
                return ResourceManager.GetString("RunProgram_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Terminate &apos;QuickLaunchOnTray&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TerminateApp {
            get {
                return ResourceManager.GetString("TerminateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;QuickLaunchOnTray&apos; 종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TerminateApp_ko {
            get {
                return ResourceManager.GetString("TerminateApp_ko", resourceCulture);
            }
        }
    }
}
